# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Web20-Validator
version:      0.01
version_from: lib/Acme/Web20/Validator.pm
installdirs:  site
requires:
    Class::Accessor:               0.01
    Class::Data::Inheritable:      0.01
    Feed::Find:                    0.01
    LWP::UserAgent:                0.01
    Module::Pluggable:             0.01
    Text::ASCIITable:              0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
